StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: sample-name
      RoleArn: arnofstatemachine
      DefinitionString:
        Fn::Sub: |
          {
            "StartAt": "CloudWatchEvent",
            "States": {
              "TriggerLambdaState": {
                "Type": "Task",
                "Resource": "${TriggerLambda.Arn}",
                "Next": "ResponseGeneratorLambdaState"
              },
              "ProcessLambdaState": {
                "Type": "Task",
                "Resource": "${ProcessLambda.Arn}",
                "Next": "ResponseGeneratorLambdaState"
              },
              "GlueJobState": {
                "Type": "Task",
                "Resource": "${glueJob.Arn}",
                "End": true
            }
          }

  ScheduledEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Scheduled event to trigger Step Functions state machine"
      ScheduleExpression: cron(0 * * * *)
      State: "ENABLED"
      Targets:
        -
          Arn: !Ref StateMachine
          Id: !GetAtt StateMachine.Name
          RoleArn: !GetAtt ScheduledEventIAMRole.Arn